"""Build a markdown postmortem and post it to a Teams incoming webhook."""
import datetime as _dt
import httpx

from .config import settings


def build_postmortem(incident: dict) -> str:
    """incident keys: alert_name, resource, root_cause, action_taken, summary, timeline(list[str])."""
    ts = _dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    timeline = "\n".join(f"- {t}" for t in incident.get("timeline", []))
    return f"""# Postmortem — {incident.get('alert_name', 'Incident')}

**Time:** {ts}
**Affected:** {incident.get('resource', 'unknown')}

## Root cause
{incident.get('root_cause', 'TBD')}

## Action taken
{incident.get('action_taken', 'none')}

## Timeline
{timeline or '- (none recorded)'}

## Summary
{incident.get('summary', '')}

*Generated by SentinelOps.*
"""


def post_to_teams(markdown: str) -> bool:
    """Post the postmortem to Teams. Falls back to stdout when no webhook is set."""
    if not settings.teams_webhook_url:
        print("[postmortem] (no TEAMS_WEBHOOK_URL set)\n" + markdown)
        return False
    payload = {"text": markdown}  # adapt to Adaptive Card / Workflows schema if needed
    r = httpx.post(settings.teams_webhook_url, json=payload, timeout=10)
    return r.status_code < 300
